-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.7
-- Fri Nov 07 19:20:49 2025

-- parameterized module component declaration
component PLL_15_76
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_15_76
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
