-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 5.7
-- Mon Jun 24 18:08:02 2024

-- parameterized module component declaration
component PLL
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
