-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.7
-- Thu Nov 06 15:22:14 2025

-- parameterized module component declaration
component PLL
    port (CLKI: in  std_logic; CLKOP: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL
    port map (CLKI=>__, CLKOP=>__);
