-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 5.7
-- Fri Aug 30 17:40:57 2024

-- parameterized module component declaration
component PLL200
    port (CLKI: in  std_logic; CLKOP: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL200
    port map (CLKI=>__, CLKOP=>__);
